### ISSUE TITLE
Create Doxygen documentation

### ISSUE THREAD

**Issue by aads500** [alexeismith/AutoDJ#13]
Doxygen can be used to auto-generate documentation based on comments within the code. The comments have deliberately been written in a [format that Doxygen will understand](https://www.doxygen.nl/manual/docblocks.html), so it should be fairly simple to generate the documentation.

**Comment by alexeismith** [comment]
Need somewhere to host the HTML files that Doxygen generates.
[https://codedocs.xyz/](https://codedocs.xyz/) works for public GitHub repos

**Comment by alexeismith** [comment]
Work-in-progress docs generated at: [https://codedocs.xyz/alexeismith/AutoDJ/annotated.html](https://codedocs.xyz/alexeismith/AutoDJ/annotated.html)
